### PR TITLE
Update GraphQLService.php

### PR DESCRIPTION
**Pull request by redboer**
This fixes issue #342

### CODE REVIEW

**Comment by markhuot** [comment]
Interesting, any idea where the `0` comes from? I'll need to check the docs to find it and then this should be good to merge.

**Comment by redboer** [comment]
I think PHP 8 being more strict it doesn’t accept null as false. In dev
mode it will doesn’t fail because it accepts true (even when it basically
want an int).

Op wo 31 mrt. 2021 om 19:24 schreef Mark Huot ***@***.***>

**Comment by redboer** [comment]
I think it doesn’t even give true in dev mode, but some int value actually.

Op wo 31 mrt. 2021 om 22:07 schreef Richard de Boer ***@***.***>

**Comment by nelhop** [comment]
When will this be merged? This bug is blocking our development right now...

**Comment by Wiejeben** [comment]
Pulled changes locally can confirm this is the perfect solution!

**Comment by mashb1t** [comment]
@markhuot thank you for merging. It would be great if this MR could be released in a stable version asap. Thanks 😊

**Comment by markhuot** [comment]
This is now included in https://github.com/markhuot/craftql/releases/tag/1.3.7

**Pull request merged**
