### PR TITLE
Update ToolsController.php

### PR DESCRIPTION
**Pull request by phoob**
Making debugging a bit easier.

### CODE REVIEW

**Comment by markhuot** [comment]
Thanks! Is this an improvement for the console command server? Because, when running behind nginx or Apache, you should see a pretty stack trace if you have `devMode` set to `true`.

**Comment by phoob** [comment]
yes – only for console command server

**Comment by markhuot** [comment]
Yup, I'm wasn't looking. Okay, let me think on this for a second. At the very least I'd like to use the `devMode` setting, like I'm doing for the native `ApiController`. But I remember seeing a really nice console-based stack trace library for PHP recently. Let me see if I can find it.

**Comment by phoob** [comment]
No worries!

**Comment by markhuot** [comment]
I'm going to merge this because it's better than what is currently there. I'm gearing up for a rewrite of the console server, at some point, and don't want to loose this.

**Pull request merged**
