### PR TITLE
Doxter Behavior

### PR DESCRIPTION
**Pull request by markhuot**
Adds support for a Doxter field type

### CODE REVIEW

**Comment by StevenLangbroek** [comment]
Queries work like a charm 💯

**Comment by markhuot** [comment]
FYI, I updated this with a breaking change. In general I'm trying to match CraftQL as closely as I can to Craft's own Twig API. By default Doxter returns `DoxterData` to the template which exposes `{{ entry.doxterField }}` for the parsed HTML and `{{ entry.doxterField.getRaw() }}` for the raw markdown. CraftQL returning an object and not the parsed html when seemed "different" when accessed through `{ entries { ...on News { doxterField } } }`.

With this update, calling the naked field now returns the parsed HTML, as you would get in a Twig template. However, if you want the raw Markdown you can pass an argument of `raw:true` (aligning to `.getRaw()`). Like this:

```graphql
{
  entries {
    ...on News {
      parsedHtml: doxterField
      rawMarkdown: doxterField(raw:true)
    }
  }
}
```

Sorry for the change, but I like this implementation better.

**Comment by StevenLangbroek** [comment]
Definitely agree, it's nice! Did you consider what to do with filters yet? I think they would be a good conceptual match to GraphQL's directives... Maybe start discussing on an issue?

**Comment by markhuot** [comment]
Yup, a separate issue would be best. https://github.com/webonyx/graphql-php supports the built in `@include` and `@skip` directives, but adding some custom directives would be interesting.

**Comment by mattstein** [comment]
FWIW, I just [submitted a PR for Doxter](https://github.com/selvinortiz/craft-plugin-doxter/pull/20) when I noticed this behavior left the CraftQL codebase. I'm only getting started with CraftQL/GraphQL, but it was pretty straightforward to get it working!

**Pull request merged**
