### PR TITLE
Directive @idNot

### PR DESCRIPTION
**Pull request by narration-sd**
Mark, would appreciate your look at this -- it's functional, if not ready for an actual PR yet.

What I've got is a base shot at the @idNot directive I need for controlling nested children in queries, with coming Live Vue. The production need comes from the model client site I've applied this to, where they used Craft Structures on 'pages' to auto-produce a menu basis.

This works, as in the attached demo screens, 
- The first shows it not affecting when the id doesn't match, so you can see all the relevant children -- first group 3-deep.
- the second shows two children taken out properly by @idNot -- ids were 574 and 733. I've skipped showing so, but taking out  any parent takes out all its children, as expected.
- the third shows that at present, query variables aren't properly passed to directives.

This took a lot of discovery to arrive at, but at  least I have a degree of understanding now on how your layers operate. The action itself seems very useful beyond the need I see, and hope you agree.

Seeing this, you might have other ideas about  how it ought to be structured, and suchmight well change also if you got to making any moves on the idea @timkelty passed in #142 about normalizing Craft lists out of Field --  if I'm happy enough  with that aspect as is (having at least conquered  there ;) ).

The part about the the query variables I do need, and figure this will be easier from your knowledge. 

I tried a number of different syntax and possible nesting approaches to get the query var in -- all gave the visible error, or ones about  wrong things in places.

I'm at the moment unclear why I had to produce the resolve query addition literally, instead of with Craft array parts, but it's late and  on a weekend. It might be good if it acted like the regular idNot code I passed you, if on the other hand PostGres looks like it uses the same syntax as MySQL here.

That's it then -- quite some effort in, but worth it to get the feature for coming users...

**Base Case - non-matching @idNot **

at-idnot-iniital-no-effect

**Working - @idNot is blocking children 574 AND 733 **

at-idnot-two-children-out

**Currently not accepting query var idNot for @idNot(in: ) values**

at-idnot-use-of-query-var-faulted

### CODE REVIEW

**Comment by narration-sd** [comment]
Remembering later had meant to say, it's very natural that the parser means for query variables and directives wouldn't be there yet, given the way they're treated in the original GraphQL. At the same time, Apollo among others looks to be much encouraging building directives of this sort, and it feels a very practical matter.

We'd always want to be considering a context's range of needs for database flexibility, but in the Craft case it doesn't look like this will often come up or be difficult if it does.

Also, I should have said 'understanding on all the layers', as most of the actual action is taking place within the GraphQl-php build and its dive through the schema. It has to be understood there, for introducing alteration through CraftQL's ability to inject into resolvers. 

If there was a change from the present handling of list-type endpoints, it would be important to preserve this injection for them. I'm thinking now also about whether it would be a good idea to contribute a doc segment for how this directive uses and allows for details of the interactions? Code is straightforward enough once you get there, but not so evident from a beginning....  

CraftQL's very nice in-CP interface really showed its strength alongside a debugger for working this out, besides how useful and pleasant it is in developing queries.

**Comment by narration-sd** [comment]
Mark, would apologise for size of late-night weekend comments - reflection on completing something, am sure you understand, and I do think there are items of interest to you. But...!

Here are a couple of items from where I've had time to to get to today, to bound any thinking you're presently able to give this:
- the 'field' argument is going to go away. It was there thinking of limiting scope, but that's already controlled by where you put the directive in the query. It's handy to leave this in at moment though, for working the second problem...
- I've got through the type system aspects of the inability to use Query Variables, though not sure if this will rise again later in another way. Perhaps not. Now I'm to the point of discovering the values of seemingly any query variable aren't actually delivered in the arguments to a directive -- just their names. That's the 'second problem', and I'll need to see if there's any way to adjust this from CraftQL level.

Ideas welcome...thanks

**Comment by narration-sd** [comment]
p.s. in a quick look, it appears apollo has had to deal with a directives-arguments  issue also;

    https://github.com/apollographql/graphql-tools/issues/649 , reading to end

And  I expect whatever's going on here accounts for that I could never get the stock skip: etc. directives to work with query vars as well.

**Comment by narration-sd** [comment]
Mark, good progress here -- after coming home tonight, got into this and worked out getting the Query Variable value/s for the directive. There are details to get this traansparent vs. inline values, and it's gotten too late to finish them now, but it will come together soon.

Since the @idNot directive itself already operates as expected, this is going to work overall. I'll let you know when the code is updated in this PR to have your look at accepting it -- or to say if you want it arranged a different way for that.

Cheers, Clive

**Comment by narration-sd** [comment]
Oh, and I did try to complete the design in a way that would make it straightforward for other @directives to be added in cases like this one  -- you can find a comment or two noting where things would go, besides the way the structure is distributed...

**Comment by markhuot** [comment]
@narration-sd, I'm sorry but I'm still struggling with this. I _think_ I've achieved the same thing by adding all the query arguments to the `children` field. So you can now do,

```graphql
{
  entries(section:pages) {
    id
    title
    children(idNot:[1950, 2458]) {
      id
      title
    }
  }
}
```

This will work the exact same way it does on the top level which means you could also do `.id` or `.limit` or, really, any other query argument.

You can see this over here: https://github.com/markhuot/craftql/pull/174/files

**Comment by narration-sd** [comment]
Yipes - wish I had known how you were thinking -- a lot of hours on this last week, since my project needed it, if advantage in learning how CraftQl/graphql-php operates.

I'll late in the day likely get a chance to pull in your alternative. Given it does the job at  hand, works within fragments, it would be nice that it adds the other query-altering possibilities also, for sure.

**Comment by markhuot** [comment]
Sounds good, let me know how your testing goes @narration-sd.

And sorry I didn't get this to you sooner. I didn't actually understand what you were looking for until I saw your PR and read through it. Now that I see what you're looking for I do think we can add the query arguments in a bunch of places. If you need it anywhere else, just let me know.

**Pull request closed without merging**
