### PR TITLE
#132 adds query arguments to entry children

### PR DESCRIPTION
**Pull request by markhuot**

### CODE REVIEW

**Comment by narration-sd** [comment]
Ok, had a chance to wring this out, and it works quite well, on fragments indeed, and as expected from internals, in the presence of id: positive selections for same elements in the environment. It does have to be used on each mention of children, but the helper system on CraftiQL catches this when you try, and explains - great.

Having looked at the pull code earlier, I can see why you'd like to do it this way. 

I'm thinking that the advantage of my method would be that it applies to any list element, without further code. So it's a trade. I went that way originally both because I didn't realize your method, and because the tendency I seemed to see from Apollo was to do directives for such things.

Either way, it's completely understandable that real use would want such extensions. At the same time as  I understand the original author's resistance, but in any case he  finally allowed how what people wanted could or should be done in resolvers, which is what either of our approaches actually accomplishes.

And then we're responsible that the extensions work with the databases to be used, his point. I think we're on firm ground with this one, as the 'not in (a, b,c....]' syntax had earlier looked into, and it seems the same for PostGres -- would think likely for others possible with Craft as well. At least until Craft goes to something NoSQL, anyway ;)

Thanks again, Mark, and I'll be using this in the Live Vue doc and demo, imagining it will get to master before long. And apologies if the need wasn't easy to understand, but it's very easy to not to see another of many possible logics, isn't it.  Why I often enough prefer stories, I guess...!

Clive

**Comment by narration-sd** [comment]
p.s. I'll close the @idNot pull, but leave it around on my fork in case warrants later any looking into.

**Comment by markhuot** [comment]
Thanks Clive! I'll merge this to `master` now.

**Comment by narration-sd** [comment]
Good man ;) and thanks!

**Pull request merged**
